name: Daily Article Generation

on:
  schedule:
    # Run every day at 9:00 AM EST (14:00 UTC during DST, 13:00 UTC otherwise)
    # Adjust based on your timezone preference
    - cron: '0 14 * * *'

  # Allow manual triggering for testing
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-article:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up environment
        run: |
          echo "Setting up article generation environment"
          sudo apt-get update
          sudo apt-get install -y jq
          chmod +x scripts/generate-daily-article.sh
          chmod +x scripts/send-notification.sh

      - name: Generate daily article
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          echo "Generating daily article using Claude API..."
          ./scripts/generate-daily-article.sh

      - name: Commit and push article
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "VOTEGTR Content Bot"

          git add drafts/

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add daily article: ${{ env.ARTICLE_TITLE }}"
            git push
            echo "✓ Article committed and pushed to repository"
          fi

      - name: Send email notification
        if: false  # Email disabled - SendGrid account under review
        continue-on-error: true
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "📝 New VOTEGTR Article Ready for Review: ${{ env.ARTICLE_TITLE }}"
          to: ${{ secrets.NOTIFICATION_EMAIL }}
          from: VOTEGTR Content System <${{ secrets.SMTP_USERNAME }}>
          html_body: |
            <!DOCTYPE html>
            <html>
            <head>
                <style>
                    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
                    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
                    .header { background-color: #0066cc; color: white; padding: 20px; border-radius: 5px; }
                    .content { background-color: #f4f4f4; padding: 20px; margin: 20px 0; border-radius: 5px; }
                    .metadata { background-color: white; padding: 15px; border-left: 4px solid #0066cc; }
                    .metadata-item { margin: 8px 0; }
                    .metadata-label { font-weight: bold; color: #0066cc; }
                    .button { display: inline-block; padding: 12px 24px; background-color: #0066cc; color: white; text-decoration: none; border-radius: 5px; margin: 10px 5px; }
                    .footer { color: #666; font-size: 12px; margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; }
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h2>✅ New Article Generated</h2>
                    </div>

                    <div class="content">
                        <h3>${{ env.ARTICLE_TITLE }}</h3>

                        <div class="metadata">
                            <div class="metadata-item">
                                <span class="metadata-label">Segment:</span> ${{ env.ARTICLE_SEGMENT }}
                            </div>
                            <div class="metadata-item">
                                <span class="metadata-label">Target Keyword:</span> ${{ env.ARTICLE_KEYWORD }}
                            </div>
                            <div class="metadata-item">
                                <span class="metadata-label">Word Count:</span> ~${{ env.ARTICLE_WORDCOUNT }} words
                            </div>
                            <div class="metadata-item">
                                <span class="metadata-label">File:</span> ${{ env.ARTICLE_PATH }}
                            </div>
                        </div>

                        <div style="margin-top: 20px;">
                            <a href="https://github.com/${{ github.repository }}/blob/main/${{ env.ARTICLE_PATH }}" class="button">📄 View on GitHub</a>
                        </div>
                    </div>

                    <div style="margin: 20px 0; padding: 15px; background-color: #fff3cd; border-left: 4px solid #ffc107; border-radius: 5px;">
                        <strong>Next Steps:</strong>
                        <ol style="margin: 10px 0;">
                            <li>Review the article on GitHub</li>
                            <li>Reply with "Approved" or provide revision feedback</li>
                            <li>After approval, article will be uploaded to WordPress as a draft</li>
                        </ol>
                    </div>

                    <div class="footer">
                        <p>This is an automated notification from the VOTEGTR Content Generation System.</p>
                        <p>Repository: <a href="https://github.com/${{ github.repository }}">${{ github.repository }}</a></p>
                    </div>
                </div>
            </body>
            </html>

      - name: Workflow summary
        run: |
          echo "## Daily Article Generation Complete ✅" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Article:** ${{ env.ARTICLE_TITLE }}" >> $GITHUB_STEP_SUMMARY
          echo "**Segment:** ${{ env.ARTICLE_SEGMENT }}" >> $GITHUB_STEP_SUMMARY
          echo "**Target Keyword:** ${{ env.ARTICLE_KEYWORD }}" >> $GITHUB_STEP_SUMMARY
          echo "**Word Count:** ~${{ env.ARTICLE_WORDCOUNT }} words" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**File:** [${{ env.ARTICLE_PATH }}](https://github.com/${{ github.repository }}/blob/main/${{ env.ARTICLE_PATH }})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Email notification sent to: ${{ secrets.NOTIFICATION_EMAIL }}" >> $GITHUB_STEP_SUMMARY
